// <auto-generated />
namespace TestMvc5Internet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Confirmation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Confirmation));
        
        string IMigrationMetadata.Id
        {
            get { return "201310251953229_Confirmation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
